# frozen_string_literal: true

module Llamaste
  # Text generated by a Model
  class Inference
    # The input model
    attr_reader :model
    # Text prompt to generate from
    attr_reader :prompt
    # The generated output
    attr_reader :output

    # Take in values for +model+ and +prompt+
    def initialize(model, prompt, **options)
      @model = model
      @prompt = prompt
    end

    # Process tokens in the background, with an optional callback +block+
    def generate(predict = 64, &block)
      string, tokens = process_tokens(model, prompt, predict, &block)
      @output = TokenSequence.new(string, tokens)
    end
  end
end
