# frozen_string_literal: true

module Llamaste
  # Text generated by a Model
  class Inference
    # Options for configuring the model context
    attr_accessor :options
    # The input model
    attr_reader :model
    # Text prompt to generate from
    attr_reader :prompt
    # The generated output
    attr_reader :output

    # Take in values for +model+, +prompt+ and +options+
    def initialize(model:, prompt: nil, **options)
      @model = model
      @prompt = prompt
      @options = options
    end

    # Process tokens with the C GPT, with an optional callback +block+
    # :yields: partial
    def generate(&block)
      @output = TokenSequence.new(*process_tokens(&block))
    end
  end
end
